<?php

namespace Kod3r\LogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SystemLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemLogRepository extends EntityRepository
{
}
